### ISSUE TITLE
Duration date picker calendars cannot be more than 1 month apart

### ISSUE THREAD

**Issue by aszenz** [mercurymedia/elm-datetime-picker#31]
First of all thanks for creating this library, I really like the design and architecture of this. 
It's my fav date picker library so far.

Just one thing I noticed that I would like to point out:

I see that the previous / next month buttons change both calendar views (left and right) in the duration date picker.
Same is the case for next / previous year.

In my opinion the two calendars should be independently navigable so that user can select dates between long date ranges.

Example:
Selecting a range date from June 2021 to October 2021 doesn't seem to be possible currently.

**Comment by jmpressman** [comment]
Hi @aszenz. Thanks for giving our library a shot!

You should still be able to select dates across a multi-month span. You just won't be able to see both selections at the same time within the picker UI. So in your case, you can select your first date in June 2021 and then navigate so that October 2021 comes into view. You should be able to see that your June selection is still there as the intermediate days will be highlighted. You can then simply select your second/end date and the date range selection should be locked in.

We actually had independently navigable months in an early prototype, but found it led to a clunkier user experience than we had hoped. In the end, we deemed coupling the two calendars was the better option and will probably stick with it.

**Comment by aszenz** [comment]
I just tried it again and understand it now.

> You should still be able to select dates across a multi-month span. You just won't be able to see both selections at the same time within the calendar UI.

This behavior can be achieved using a single month calendar as well so showing the second month calendar is not useful.

Right now the second month calendar is only useful if u wish to select dates that are only a month apart. 

Is there an assumption that the date range is likely to be less than a month apart so the picker optimizes that scenario but neglects the longer ranges scenario ?

> We actually had independently navigable months in an early prototype

That's super interesting because there's three sets of buttons in the current duration picker view.

One is at the top (picker header), the other two are on each calendar view. I find that redundant since they all do the same thing, i.e they move both calendars forwards/backwards by month/year.

My initial expectation was that prev and next buttons on the picker would behave as you described , changing both calendars but the individual buttons on each calendar would only change their own views.

This is the way I think about it in terms of types:

```elm
type Msg = 
   -- Messages emitted by the Left Calendar
     LeftCalendarShowNextMonth
   | LeftCalendarShowPreviousMonth
   | LeftCalendarShowNextYear
   | LeftCalendarShowPreviousYear
   -- Messages emitted by the Right Calendar
   | RightCalendarShowNextMonth
   | RightCalendarShowPreviousMonth
   | RightCalendarShowNextYear
   | RightCalendarShowPreviousYear
  -- Messages emitted by the picker header
   | BothCalendarShowNextMonth
   | BothCalendarShowPreviousMonth
   | BothCalendarShowNextYear
   | BothCalendarShowPreviousYear
```

Hopefully I explained it right, if not i can capture a video highlighting this point

**Comment by jmpressman** [comment]
> Is there an assumption that the date range is likely to be less than a month apart so the picker optimizes that scenario but neglects the longer ranges scenario ?

Yes. To go into a bit more detail regarding our decision we found that most users who tried the picker with independent calendars found they preferred the coupled version because it involved less "clicking around".

> That's super interesting because there's three sets of buttons in the current duration picker view.

What version are you using? I have attached a screenshot from the current duration demo and there are only two sets of buttons:  one for navigating from month-to-month and one for navigating from year-to-year.

<img width="565" alt="Screenshot 2021-06-24 at 10 20 53" src="https://user-images.githubusercontent.com/20546636/123228662-e92b8c80-d4d5-11eb-9120-9c3e3cd42a23.png">

**Comment by aszenz** [comment]
> Yes. To go into a bit more detail regarding our decision we found that most users who tried the picker with independent calendars found they preferred the coupled version because it involved less "clicking around".

That makes a lot of sense, thanks for providing the explanation.

> What version are you using?

My apologies, I actually had modified the picker previously which caused the two individual calendar buttons to show up. 

I usually copy library code instead of installing them in elm so that I can freely modify them but it makes it harder to understand where the behavior is coming from. 

Anyways, it seems we are all good here, I do feel a temptation to make the individual calendar buttons show up based on a setting. But feel free to close this issue.

**Comment by jmpressman** [comment]
Happy to have helped! I'll close this for now.
